"""
Report builder — assembles all Markdown sections into the final report.
"""

import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

import pandas as pd

from src.report.sections import (
    section_header,
    section_risk_dashboard,
    section_top_risk_accounts,
    section_expansion_opportunities,
    section_cross_regional_patterns,
    section_approved_comments,
    section_appendix,
)

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).parent.parent.parent


def build_report_markdown(
    scored_df: pd.DataFrame,
    session=None,
    include_appendix: bool = True,
) -> str:
    """
    Assemble all report sections into a single Markdown string.

    Args:
        scored_df: Scored master DataFrame.
        session: SessionState with decisions (or None for data-only report).
        include_appendix: Whether to include the full account list appendix.

    Returns:
        Complete Markdown report string.
    """
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    parts = [
        section_header(scored_df, session, generated_at),
        section_risk_dashboard(scored_df),
        section_top_risk_accounts(scored_df, session, top_n=10),
        section_expansion_opportunities(scored_df, session, top_n=10),
        section_cross_regional_patterns(scored_df),
        section_approved_comments(scored_df, session),
    ]
    if include_appendix:
        parts.append(section_appendix(scored_df, session))

    parts.append(
        f"\n---\n*Generated by Global Account Review Agent v1.0 "
        f"on {generated_at}*\n"
    )
    return "\n".join(parts)


def save_report(
    scored_df: pd.DataFrame,
    session=None,
    output_dir: str = "data/output",
) -> Path:
    """
    Build and save the Markdown report to a file.

    Args:
        scored_df: Scored master DataFrame.
        session: SessionState.
        output_dir: Directory to write the report (relative to project root).

    Returns:
        Path of the written file.
    """
    report_md = build_report_markdown(scored_df, session)
    session_id = session.session_id if session else datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"cro_review_{session_id}.md"

    output_path = PROJECT_ROOT / output_dir / filename
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report_md, encoding="utf-8")

    logger.info("Report saved: %s", output_path)
    return output_path
